### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by piravp** [piravp/series-manager#1]
### Major
* [ ] Help page
  * Info about how to use the site w/ images/gifs
* [ ] Home page
   * Colorize genres
   * Create own genres
   * Sort series in a new view (other than Card) which is sorted according to the users current mood
        * Comedy mood? Action mood? 
   * User should be able to manually add their own series in `/home` if it can't be found in `/search` (#10)
   * Import/export (json) file with all your series - share amongst friends or what not.
       * http://danml.com/download.html
* [ ] DiscoverPage (Filter by different parameters)
* [ ] Calendar (#20)
   * Show season premiere in a [calendar](https://ant.design/components/calendar/) of the shows that user has in their list *and* has ticked off for notification.
  * Season premiere notification
* [ ] Recommender system using Machine Learning (#11)
* [ ] **Refactor so that Redux, and Redux alone, is responsible for fetching data**
  * Fetch data from the API using action and use the redux-promise middleware to return payload instead of Promise
  * Reselector library which is a redux lib to do some calculation on two pieces of redux state (looks like it might be useful for filtering and such) and return one new state
* [ ] **Code refactoring**
  * Extract Pages into its own folder called Containers/Pages?
* [ ] Make lists shareable between friends (read-only)
* [ ] Stats about the user activity (where are most of the users series from, minutes watched in total)
   * https://www.highcharts.com/

### Low priority features/fixes
* [ ] Home
   * Let user change size of the cards
      * Use cookies to remember choice
   * Rate series in users own list
      * https://ant.design/components/rate/
* [ ] https://auth0.com/
* [ ] https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout
* Make mobile friendly
* [ ] HTTPS
* [ ] URL Shortener (Search)?
* [ ] Better carousel in `popular`? https://eleme.github.io/element-react/#/en-US/carousel

**Other components**
* Icons: http://ionicons.com/
* https://developer.microsoft.com/en-us/fabric#/components/teachingbubble

### Analytics and Feedback tools
Should explore the possibility to use analytics tools to mine data about user behavior which can in turn be used for ML (#11) purposes. 
* https://metrica.yandex.com/about? 
* https://getsitecontrol.com/ (surveys, lead forms, contact forms, live chats)

### APIs
* https://trakt.docs.apiary.io
* ~~https://api.guidebox.com/ (Only for commercial use)~~

## Other
* [ ] Split webpack config files
  * https://simonsmith.io/organising-webpack-config-environments/

## Testing
* [x] jest 
* [x] Tracis CI 
* [ ] Docker 
  * http://mherman.org/blog/2017/12/07/dockerizing-a-react-app/
  * https://developer.ibm.com/code/patterns/deploy-a-react-application-on-kubernetes/
  * https://www.youtube.com/watch?v=1Lq9vW3LuH8
* [ ] coverall

## Deployment
* [ ] DigitalOcean / CloudFlare / Google Firebase
* [ ] Deep Learning: Microsoft Azure / AWS / Google Cloud
