### ISSUE TITLE
Show timeline with user activity

### ISSUE THREAD

**Issue by piravp** [piravp/series-manager#18]
**Description**
Create a [timeline](https://ant.design/components/timeline/) showing the users activity. E.g. *added show*, *removed show* with the ability to clear the timeline. 

**To-Do**
* [x] Basic functionality
* [x] Persists timeline in localstorage
* [ ] Contain the content in the modal to a certain (scrollable) area
* [ ] Write tests
* [ ] Remove one event _(use node-uuid to uniquely identify each event?)_
* [x] Remove all events
